-- Roma's Donuts COE controlled e-signature workflow
-- Prepared 2026-09-16. Apply only after explicit production-migration approval.
-- Additive only: no existing COE rows are deleted or rewritten by this migration.

begin;

create table if not exists public.coe_authorized_signatories (
  admin_user_id uuid primary key references public.admin_users(id) on delete cascade,
  signatory_title text not null default 'Authorized Signatory',
  signature_profile_path text,
  is_active boolean not null default true,
  authorized_by uuid references public.admin_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coe_signature_requests (
  document_record_id uuid primary key references public.company_document_records(id) on delete cascade,
  state text not null default 'draft' check (state in ('draft','pending','returned','signed','released')),
  requested_by_admin_user_id uuid references public.admin_users(id) on delete set null,
  assigned_signatory_admin_user_id uuid references public.admin_users(id) on delete set null,
  requested_at timestamptz,
  returned_at timestamptz,
  return_reason text,
  signed_at timestamptz,
  signed_name text,
  signed_title text,
  signed_signature_path text,
  document_hash text,
  version integer not null default 0,
  released_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint coe_signature_hash_format check (document_hash is null or document_hash ~ '^[0-9a-f]{64}$')
);

create table if not exists public.coe_signature_audit_log (
  id bigint generated by default as identity primary key,
  document_record_id uuid references public.company_document_records(id) on delete set null,
  actor_admin_user_id uuid references public.admin_users(id) on delete set null,
  actor_name text,
  action_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists coe_signature_requests_assigned_state_idx
  on public.coe_signature_requests (assigned_signatory_admin_user_id, state, requested_at desc);
create index if not exists coe_signature_requests_requested_by_idx
  on public.coe_signature_requests (requested_by_admin_user_id, requested_at desc);
create index if not exists coe_signature_audit_document_idx
  on public.coe_signature_audit_log (document_record_id, created_at desc);

alter table public.coe_authorized_signatories enable row level security;
alter table public.coe_signature_requests enable row level security;
alter table public.coe_signature_audit_log enable row level security;

revoke all on table public.coe_authorized_signatories from anon, authenticated;
revoke all on table public.coe_signature_requests from anon, authenticated;
revoke all on table public.coe_signature_audit_log from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'coe-signatures',
  'coe-signatures',
  false,
  2097152,
  array['image/png','image/jpeg','image/webp']::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.coe_log_signature_audit(
  p_action text,
  p_document_record_id uuid default null,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin record;
begin
  select id, full_name, upper(coalesce(role,'')) as role
  into v_admin
  from public.admin_users
  where auth_user_id = auth.uid() and is_active = true
  order by created_at asc
  limit 1;

  if v_admin.id is null then
    raise exception 'Active admin session required.';
  end if;

  insert into public.coe_signature_audit_log (
    document_record_id, actor_admin_user_id, actor_name, action_type, details
  ) values (
    p_document_record_id,
    v_admin.id,
    v_admin.full_name,
    trim(coalesce(p_action,'COE SIGNATURE ACTION')),
    coalesce(p_details, '{}'::jsonb) || jsonb_build_object('actor_role',v_admin.role)
  );
end;
$$;
revoke all on function public.coe_log_signature_audit(text,uuid,jsonb) from public, anon, authenticated;

create or replace function public.get_my_coe_signatory_profile()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin record;
  v_signatory public.coe_authorized_signatories%rowtype;
begin
  select id, full_name, upper(coalesce(role,'')) as role
  into v_admin
  from public.admin_users
  where auth_user_id = auth.uid() and is_active = true
  order by created_at asc
  limit 1;

  if v_admin.id is null then raise exception 'Active admin session required.'; end if;

  select * into v_signatory
  from public.coe_authorized_signatories
  where admin_user_id = v_admin.id;

  return jsonb_build_object(
    'admin_user_id', v_admin.id,
    'admin_name', v_admin.full_name,
    'admin_role', v_admin.role,
    'authorized', coalesce(v_signatory.is_active, false),
    'signatory_title', coalesce(v_signatory.signatory_title, 'Authorized Signatory'),
    'signature_profile_path', v_signatory.signature_profile_path
  );
end;
$$;
revoke all on function public.get_my_coe_signatory_profile() from public, anon;
grant execute on function public.get_my_coe_signatory_profile() to authenticated;

create or replace function public.list_active_coe_signatories()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_caller record;
begin
  select id, upper(coalesce(role,'')) as role
  into v_caller
  from public.admin_users
  where auth_user_id = auth.uid() and is_active = true
  order by created_at asc
  limit 1;

  if v_caller.id is null then raise exception 'Active admin session required.'; end if;
  if v_caller.role not in ('OWNER','HR','ADMIN','MANAGER') then
    raise exception 'You are not authorized to send COEs for signature.';
  end if;

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'admin_user_id', au.id,
        'admin_name', au.full_name,
        'admin_role', upper(coalesce(au.role,'')),
        'signatory_title', cs.signatory_title,
        'has_signature_profile', (cs.signature_profile_path is not null and cs.signature_profile_path <> '')
      ) order by au.full_name
    )
    from public.coe_authorized_signatories cs
    join public.admin_users au on au.id = cs.admin_user_id
    where cs.is_active = true and au.is_active = true
  ), '[]'::jsonb);
end;
$$;
revoke all on function public.list_active_coe_signatories() from public, anon;
grant execute on function public.list_active_coe_signatories() to authenticated;

create or replace function public.list_coe_signatory_candidates()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_owner_id uuid;
begin
  select id into v_owner_id
  from public.admin_users
  where auth_user_id = auth.uid()
    and is_active = true
    and upper(coalesce(role,'')) = 'OWNER'
  order by created_at asc
  limit 1;

  if v_owner_id is null then raise exception 'Owner authorization required.'; end if;

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'admin_user_id', au.id,
        'admin_name', au.full_name,
        'admin_role', upper(coalesce(au.role,'')),
        'authorized', coalesce(cs.is_active,false),
        'signatory_title', coalesce(cs.signatory_title,'Authorized Signatory'),
        'has_signature_profile', (cs.signature_profile_path is not null and cs.signature_profile_path <> '')
      ) order by au.full_name
    )
    from public.admin_users au
    left join public.coe_authorized_signatories cs on cs.admin_user_id = au.id
    where au.is_active = true
  ), '[]'::jsonb);
end;
$$;
revoke all on function public.list_coe_signatory_candidates() from public, anon;
grant execute on function public.list_coe_signatory_candidates() to authenticated;

create or replace function public.set_coe_authorized_signatory(
  p_admin_user_id uuid,
  p_enabled boolean,
  p_signatory_title text default 'Authorized Signatory'
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_owner record;
  v_target_name text;
  v_title text := nullif(trim(coalesce(p_signatory_title,'')), '');
begin
  select id, full_name, upper(coalesce(role,'')) as role
  into v_owner
  from public.admin_users
  where auth_user_id = auth.uid()
    and is_active = true
    and upper(coalesce(role,'')) = 'OWNER'
  order by created_at asc
  limit 1;

  if v_owner.id is null then raise exception 'Owner authorization required.'; end if;

  select full_name into v_target_name
  from public.admin_users
  where id = p_admin_user_id and is_active = true;

  if v_target_name is null then raise exception 'The selected admin account is not active.'; end if;

  insert into public.coe_authorized_signatories (
    admin_user_id, signatory_title, is_active, authorized_by, updated_at
  ) values (
    p_admin_user_id, coalesce(v_title,'Authorized Signatory'), coalesce(p_enabled,false), v_owner.id, now()
  )
  on conflict (admin_user_id) do update
  set signatory_title = excluded.signatory_title,
      is_active = excluded.is_active,
      authorized_by = excluded.authorized_by,
      updated_at = now();

  perform public.coe_log_signature_audit(
    case when p_enabled then 'COE SIGNATORY AUTHORIZED' else 'COE SIGNATORY DISABLED' end,
    null,
    jsonb_build_object('target_admin_user_id',p_admin_user_id,'target_name',v_target_name,'signatory_title',coalesce(v_title,'Authorized Signatory'))
  );

  return jsonb_build_object('ok',true,'admin_user_id',p_admin_user_id,'authorized',coalesce(p_enabled,false));
end;
$$;
revoke all on function public.set_coe_authorized_signatory(uuid,boolean,text) from public, anon;
grant execute on function public.set_coe_authorized_signatory(uuid,boolean,text) to authenticated;

create or replace function public.set_my_coe_signature_profile(p_signature_profile_path text)
returns jsonb
language plpgsql
security definer
set search_path = public, storage, pg_temp
as $$
declare
  v_admin record;
  v_path text := trim(coalesce(p_signature_profile_path,''));
begin
  select au.id, au.full_name, cs.signatory_title
  into v_admin
  from public.admin_users au
  join public.coe_authorized_signatories cs on cs.admin_user_id = au.id and cs.is_active = true
  where au.auth_user_id = auth.uid() and au.is_active = true
  order by au.created_at asc
  limit 1;

  if v_admin.id is null then raise exception 'Authorized signatory access required.'; end if;
  if v_path = '' or v_path not like ('profiles/' || v_admin.id::text || '/%') then raise exception 'Invalid signature profile path.'; end if;

  if not exists (
    select 1 from storage.objects
    where bucket_id = 'coe-signatures' and name = v_path
  ) then
    raise exception 'Signature image was not found in secure storage.';
  end if;

  update public.coe_authorized_signatories
  set signature_profile_path = v_path, updated_at = now()
  where admin_user_id = v_admin.id and is_active = true;

  perform public.coe_log_signature_audit(
    'COE SIGNATURE PROFILE UPDATED',
    null,
    jsonb_build_object('storage_path',v_path)
  );

  return jsonb_build_object('ok',true,'signature_profile_path',v_path);
end;
$$;
revoke all on function public.set_my_coe_signature_profile(text) from public, anon;
grant execute on function public.set_my_coe_signature_profile(text) to authenticated;

create or replace function public.request_coe_signature(
  p_document_record_id uuid,
  p_signatory_admin_user_id uuid,
  p_document_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_caller record;
  v_document record;
  v_signatory record;
  v_hash text := lower(trim(coalesce(p_document_hash,'')));
begin
  select id, full_name, upper(coalesce(role,'')) as role
  into v_caller
  from public.admin_users
  where auth_user_id = auth.uid() and is_active = true
  order by created_at asc
  limit 1;
  if v_caller.id is null then raise exception 'Active admin session required.'; end if;
  if v_caller.role not in ('OWNER','HR','ADMIN','MANAGER') then raise exception 'You are not authorized to send COEs for signature.'; end if;
  if v_hash !~ '^[0-9a-f]{64}$' then raise exception 'Invalid COE content hash.'; end if;

  select id, form_key, document_no, employee_name
  into v_document
  from public.company_document_records
  where id = p_document_record_id;
  if v_document.id is null then raise exception 'COE record not found.'; end if;
  if upper(replace(coalesce(v_document.form_key,''),'_','-')) <> 'HR-COE' then raise exception 'The selected record is not a Certificate of Employment.'; end if;

  select au.id, au.full_name, cs.signatory_title
  into v_signatory
  from public.admin_users au
  join public.coe_authorized_signatories cs on cs.admin_user_id = au.id and cs.is_active = true
  where au.id = p_signatory_admin_user_id and au.is_active = true;
  if v_signatory.id is null then raise exception 'The selected COE signatory is not authorized or active.'; end if;

  insert into public.coe_signature_requests (
    document_record_id, state, requested_by_admin_user_id, assigned_signatory_admin_user_id,
    requested_at, returned_at, return_reason, signed_at, signed_name, signed_title,
    signed_signature_path, document_hash, version, released_at, updated_at
  ) values (
    p_document_record_id, 'pending', v_caller.id, v_signatory.id,
    now(), null, null, null, null, null,
    null, v_hash, 1, null, now()
  )
  on conflict (document_record_id) do update
  set state = 'pending',
      requested_by_admin_user_id = excluded.requested_by_admin_user_id,
      assigned_signatory_admin_user_id = excluded.assigned_signatory_admin_user_id,
      requested_at = now(),
      returned_at = null,
      return_reason = null,
      signed_at = null,
      signed_name = null,
      signed_title = null,
      signed_signature_path = null,
      document_hash = excluded.document_hash,
      version = public.coe_signature_requests.version + 1,
      released_at = null,
      updated_at = now();

  update public.company_document_records
  set status = 'Pending Signature', updated_at = now()
  where id = p_document_record_id;

  perform public.coe_log_signature_audit(
    'COE SENT FOR SIGNATURE',
    p_document_record_id,
    jsonb_build_object(
      'document_no',v_document.document_no,
      'employee_name',v_document.employee_name,
      'signatory_admin_user_id',v_signatory.id,
      'signatory_name',v_signatory.full_name,
      'document_hash',v_hash
    )
  );

  return jsonb_build_object('ok',true,'state','pending','document_record_id',p_document_record_id,'assigned_signatory_name',v_signatory.full_name);
end;
$$;
revoke all on function public.request_coe_signature(uuid,uuid,text) from public, anon;
grant execute on function public.request_coe_signature(uuid,uuid,text) to authenticated;

create or replace function public.get_coe_signature_state(p_document_record_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_caller record;
  v_request record;
begin
  select id, full_name, upper(coalesce(role,'')) as role
  into v_caller
  from public.admin_users
  where auth_user_id = auth.uid() and is_active = true
  order by created_at asc
  limit 1;
  if v_caller.id is null then raise exception 'Active admin session required.'; end if;

  if not exists (
    select 1 from public.company_document_records
    where id = p_document_record_id and upper(replace(coalesce(form_key,''),'_','-')) = 'HR-COE'
  ) then raise exception 'COE record not found.'; end if;

  select r.*,
         requester.full_name as requested_by_name,
         signer.full_name as assigned_signatory_name
  into v_request
  from public.coe_signature_requests r
  left join public.admin_users requester on requester.id = r.requested_by_admin_user_id
  left join public.admin_users signer on signer.id = r.assigned_signatory_admin_user_id
  where r.document_record_id = p_document_record_id;

  if v_request.document_record_id is null then
    if v_caller.role not in ('OWNER','HR','ADMIN','MANAGER') then raise exception 'You are not authorized to manage this COE.'; end if;
    return jsonb_build_object(
      'document_record_id',p_document_record_id,
      'state','draft',
      'can_sign',false,
      'can_request',true,
      'can_manage',(v_caller.role = 'OWNER')
    );
  end if;

  if not (
    v_caller.role in ('OWNER','HR','ADMIN','MANAGER')
    or v_request.requested_by_admin_user_id = v_caller.id
    or v_request.assigned_signatory_admin_user_id = v_caller.id
  ) then raise exception 'You are not authorized to access this COE signature workflow.'; end if;

  return jsonb_build_object(
    'document_record_id',v_request.document_record_id,
    'state',v_request.state,
    'requested_at',v_request.requested_at,
    'requested_by_name',v_request.requested_by_name,
    'assigned_signatory_admin_user_id',v_request.assigned_signatory_admin_user_id,
    'assigned_signatory_name',v_request.assigned_signatory_name,
    'returned_at',v_request.returned_at,
    'return_reason',v_request.return_reason,
    'signed_at',v_request.signed_at,
    'signed_name',v_request.signed_name,
    'signed_title',v_request.signed_title,
    'signed_signature_path',v_request.signed_signature_path,
    'document_hash',v_request.document_hash,
    'version',v_request.version,
    'released_at',v_request.released_at,
    'can_sign',(
      v_request.state = 'pending'
      and v_request.assigned_signatory_admin_user_id = v_caller.id
      and exists (select 1 from public.coe_authorized_signatories cs where cs.admin_user_id = v_caller.id and cs.is_active = true)
    ),
    'can_request',(v_caller.role in ('OWNER','HR','ADMIN','MANAGER')),
    'can_manage',(v_caller.role = 'OWNER')
  );
end;
$$;
revoke all on function public.get_coe_signature_state(uuid) from public, anon;
grant execute on function public.get_coe_signature_state(uuid) to authenticated;

create or replace function public.list_my_coe_signature_inbox()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin_id uuid;
begin
  select au.id into v_admin_id
  from public.admin_users au
  join public.coe_authorized_signatories cs on cs.admin_user_id = au.id and cs.is_active = true
  where au.auth_user_id = auth.uid() and au.is_active = true
  order by au.created_at asc
  limit 1;

  if v_admin_id is null then return '[]'::jsonb; end if;

  return coalesce((
    select jsonb_agg(row_data order by requested_at desc)
    from (
      select jsonb_build_object(
        'document_record_id',r.document_record_id,
        'state',r.state,
        'requested_at',r.requested_at,
        'requested_by_name',requester.full_name,
        'reference_no',d.document_no,
        'document_no',d.document_no,
        'employee_name',d.employee_name,
        'title',d.document_type,
        'record_date',d.document_date
      ) as row_data,
      r.requested_at
      from public.coe_signature_requests r
      join public.company_document_records d on d.id = r.document_record_id
      left join public.admin_users requester on requester.id = r.requested_by_admin_user_id
      where r.assigned_signatory_admin_user_id = v_admin_id
        and r.state = 'pending'
    ) inbox
  ), '[]'::jsonb);
end;
$$;
revoke all on function public.list_my_coe_signature_inbox() from public, anon;
grant execute on function public.list_my_coe_signature_inbox() to authenticated;

create or replace function public.return_coe_signature_request(
  p_document_record_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin record;
  v_reason text := trim(coalesce(p_reason,''));
begin
  select au.id, au.full_name, upper(coalesce(au.role,'')) as role
  into v_admin
  from public.admin_users au
  join public.coe_authorized_signatories cs on cs.admin_user_id = au.id and cs.is_active = true
  where au.auth_user_id = auth.uid() and au.is_active = true
  order by au.created_at asc
  limit 1;

  if v_admin.id is null then raise exception 'Authorized signatory access required.'; end if;
  if v_reason = '' then raise exception 'A correction reason is required.'; end if;

  update public.coe_signature_requests
  set state = 'returned', returned_at = now(), return_reason = v_reason, updated_at = now()
  where document_record_id = p_document_record_id
    and state = 'pending'
    and assigned_signatory_admin_user_id = v_admin.id;

  if not found then raise exception 'This COE is not pending your signature.'; end if;

  update public.company_document_records set status = 'Returned', updated_at = now() where id = p_document_record_id;

  perform public.coe_log_signature_audit(
    'COE RETURNED FOR CORRECTION',
    p_document_record_id,
    jsonb_build_object('reason',v_reason)
  );

  return jsonb_build_object('ok',true,'state','returned','return_reason',v_reason);
end;
$$;
revoke all on function public.return_coe_signature_request(uuid,text) from public, anon;
grant execute on function public.return_coe_signature_request(uuid,text) to authenticated;

create or replace function public.approve_coe_signature_request(
  p_document_record_id uuid,
  p_signature_storage_path text,
  p_document_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = public, storage, pg_temp
as $$
declare
  v_admin record;
  v_request public.coe_signature_requests%rowtype;
  v_path text := trim(coalesce(p_signature_storage_path,''));
  v_hash text := lower(trim(coalesce(p_document_hash,'')));
  v_signed_at timestamptz := now();
begin
  select au.id, au.full_name, upper(coalesce(au.role,'')) as role, cs.signatory_title
  into v_admin
  from public.admin_users au
  join public.coe_authorized_signatories cs on cs.admin_user_id = au.id and cs.is_active = true
  where au.auth_user_id = auth.uid() and au.is_active = true
  order by au.created_at asc
  limit 1;
  if v_admin.id is null then raise exception 'Authorized signatory access required.'; end if;

  select * into v_request
  from public.coe_signature_requests
  where document_record_id = p_document_record_id
  for update;

  if v_request.document_record_id is null then raise exception 'Signature request not found.'; end if;
  if v_request.state <> 'pending' then raise exception 'This COE is no longer pending signature.'; end if;
  if v_request.assigned_signatory_admin_user_id <> v_admin.id then raise exception 'This COE is assigned to a different authorized signatory.'; end if;
  if v_hash !~ '^[0-9a-f]{64}$' or v_request.document_hash <> v_hash then raise exception 'The COE content changed after it was sent for signature.'; end if;
  if v_path = '' or v_path not like ('documents/' || p_document_record_id::text || '/%') then raise exception 'Invalid signed signature path.'; end if;

  if not exists (
    select 1 from storage.objects
    where bucket_id = 'coe-signatures' and name = v_path
  ) then raise exception 'Signed signature image was not found in secure storage.'; end if;

  update public.coe_signature_requests
  set state = 'signed',
      signed_at = v_signed_at,
      signed_name = v_admin.full_name,
      signed_title = coalesce(nullif(trim(v_admin.signatory_title),''),'Authorized Signatory'),
      signed_signature_path = v_path,
      returned_at = null,
      return_reason = null,
      updated_at = now()
  where document_record_id = p_document_record_id;

  update public.company_document_records
  set status = 'Signed',
      approved_by = v_admin.full_name,
      owner_approved_by = case when v_admin.role = 'OWNER' then v_admin.full_name else owner_approved_by end,
      owner_approved_at = case when v_admin.role = 'OWNER' then v_signed_at else owner_approved_at end,
      updated_at = now()
  where id = p_document_record_id;

  perform public.coe_log_signature_audit(
    'COE E-SIGNED AND APPROVED',
    p_document_record_id,
    jsonb_build_object('signed_name',v_admin.full_name,'signed_title',v_admin.signatory_title,'document_hash',v_hash,'signature_path',v_path)
  );

  return jsonb_build_object(
    'ok',true,
    'state','signed',
    'signed_name',v_admin.full_name,
    'signed_title',coalesce(nullif(trim(v_admin.signatory_title),''),'Authorized Signatory'),
    'signed_at',v_signed_at,
    'signed_signature_path',v_path,
    'document_hash',v_hash
  );
end;
$$;
revoke all on function public.approve_coe_signature_request(uuid,text,text) from public, anon;
grant execute on function public.approve_coe_signature_request(uuid,text,text) to authenticated;

create or replace function public.invalidate_coe_signature_if_changed(
  p_document_record_id uuid,
  p_current_document_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin record;
  v_request public.coe_signature_requests%rowtype;
  v_hash text := lower(trim(coalesce(p_current_document_hash,'')));
begin
  select id, upper(coalesce(role,'')) as role
  into v_admin
  from public.admin_users
  where auth_user_id = auth.uid() and is_active = true
  order by created_at asc
  limit 1;
  if v_admin.id is null then raise exception 'Active admin session required.'; end if;
  if v_hash !~ '^[0-9a-f]{64}$' then raise exception 'Invalid COE content hash.'; end if;

  select * into v_request
  from public.coe_signature_requests
  where document_record_id = p_document_record_id
  for update;

  if v_request.document_record_id is null then
    if v_admin.role not in ('OWNER','HR','ADMIN','MANAGER') then raise exception 'You are not authorized to manage this COE.'; end if;
    return jsonb_build_object('document_record_id',p_document_record_id,'state','draft','document_hash',v_hash);
  end if;

  if not (
    v_admin.role in ('OWNER','HR','ADMIN','MANAGER')
    or v_request.requested_by_admin_user_id = v_admin.id
    or v_request.assigned_signatory_admin_user_id = v_admin.id
  ) then raise exception 'You are not authorized to manage this COE.'; end if;

  if v_request.state in ('signed','released') and v_request.document_hash is distinct from v_hash then
    update public.coe_signature_requests
    set state = 'draft',
        signed_at = null,
        signed_name = null,
        signed_title = null,
        signed_signature_path = null,
        document_hash = v_hash,
        released_at = null,
        updated_at = now()
    where document_record_id = p_document_record_id;

    update public.company_document_records
    set status = 'Draft', approved_by = null, updated_at = now()
    where id = p_document_record_id;

    perform public.coe_log_signature_audit(
      'COE SIGNATURE INVALIDATED AFTER CONTENT CHANGE',
      p_document_record_id,
      jsonb_build_object('previous_hash',v_request.document_hash,'current_hash',v_hash)
    );

    return jsonb_build_object('document_record_id',p_document_record_id,'state','draft','document_hash',v_hash,'signature_invalidated',true,'can_request',true);
  end if;

  return jsonb_build_object(
    'document_record_id',p_document_record_id,
    'state',v_request.state,
    'document_hash',v_request.document_hash,
    'signed_at',v_request.signed_at,
    'signed_name',v_request.signed_name,
    'signed_title',v_request.signed_title,
    'signed_signature_path',v_request.signed_signature_path,
    'signature_invalidated',false,
    'can_request',(v_admin.role in ('OWNER','HR','ADMIN','MANAGER'))
  );
end;
$$;
revoke all on function public.invalidate_coe_signature_if_changed(uuid,text) from public, anon;
grant execute on function public.invalidate_coe_signature_if_changed(uuid,text) to authenticated;

create or replace function public.log_coe_signature_output(
  p_document_record_id uuid,
  p_output_type text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin record;
  v_output text := upper(trim(coalesce(p_output_type,'')));
  v_request public.coe_signature_requests%rowtype;
begin
  select id, upper(coalesce(role,'')) as role
  into v_admin
  from public.admin_users
  where auth_user_id = auth.uid() and is_active = true
  order by created_at asc
  limit 1;
  if v_admin.id is null then raise exception 'Active admin session required.'; end if;
  if v_output not in ('PRINT','PDF','WORD') then raise exception 'Unsupported COE output type.'; end if;

  select * into v_request from public.coe_signature_requests where document_record_id = p_document_record_id;
  if v_request.document_record_id is null or v_request.state not in ('signed','released') then raise exception 'Final COE output requires a signed document.'; end if;
  if not (
    v_admin.role in ('OWNER','HR','ADMIN','MANAGER')
    or v_request.requested_by_admin_user_id = v_admin.id
    or v_request.assigned_signatory_admin_user_id = v_admin.id
  ) then raise exception 'You are not authorized to output this signed COE.'; end if;

  perform public.coe_log_signature_audit(
    'SIGNED COE ' || v_output || ' OUTPUT',
    p_document_record_id,
    jsonb_build_object('output_type',v_output)
  );

  return jsonb_build_object('ok',true,'output_type',v_output);
end;
$$;
revoke all on function public.log_coe_signature_output(uuid,text) from public, anon;
grant execute on function public.log_coe_signature_output(uuid,text) to authenticated;

create or replace function public.coe_signature_storage_can_read(p_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin record;
  v_parts text[] := storage.foldername(coalesce(p_name,''));
  v_document_id uuid;
begin
  select id, upper(coalesce(role,'')) as role
  into v_admin
  from public.admin_users
  where auth_user_id = auth.uid() and is_active = true
  order by created_at asc
  limit 1;
  if v_admin.id is null then return false; end if;

  if array_length(v_parts,1) >= 2 and v_parts[1] = 'profiles' then
    return v_parts[2] = v_admin.id::text
      and exists (select 1 from public.coe_authorized_signatories cs where cs.admin_user_id = v_admin.id and cs.is_active = true);
  end if;

  if array_length(v_parts,1) >= 2 and v_parts[1] = 'documents' then
    begin v_document_id := v_parts[2]::uuid; exception when others then return false; end;
    return exists (
      select 1
      from public.coe_signature_requests r
      where r.document_record_id = v_document_id
        and r.signed_signature_path = p_name
        and r.state in ('signed','released')
        and (
          v_admin.role in ('OWNER','HR','ADMIN','MANAGER')
          or r.requested_by_admin_user_id = v_admin.id
          or r.assigned_signatory_admin_user_id = v_admin.id
        )
    );
  end if;

  return false;
end;
$$;
revoke all on function public.coe_signature_storage_can_read(text) from public, anon;
grant execute on function public.coe_signature_storage_can_read(text) to authenticated;

create or replace function public.coe_signature_storage_can_write(p_name text, p_operation text)
returns boolean
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_admin_id uuid;
  v_parts text[] := storage.foldername(coalesce(p_name,''));
  v_document_id uuid;
  v_operation text := upper(trim(coalesce(p_operation,'')));
begin
  select au.id into v_admin_id
  from public.admin_users au
  join public.coe_authorized_signatories cs on cs.admin_user_id = au.id and cs.is_active = true
  where au.auth_user_id = auth.uid() and au.is_active = true
  order by au.created_at asc
  limit 1;
  if v_admin_id is null then return false; end if;

  if array_length(v_parts,1) >= 2 and v_parts[1] = 'profiles' then
    return v_parts[2] = v_admin_id::text and v_operation in ('INSERT','UPDATE','DELETE');
  end if;

  if array_length(v_parts,1) >= 2 and v_parts[1] = 'documents' then
    begin v_document_id := v_parts[2]::uuid; exception when others then return false; end;
    return v_operation in ('INSERT','DELETE')
      and exists (
        select 1 from public.coe_signature_requests r
        where r.document_record_id = v_document_id
          and r.assigned_signatory_admin_user_id = v_admin_id
          and r.state = 'pending'
      );
  end if;

  return false;
end;
$$;
revoke all on function public.coe_signature_storage_can_write(text,text) from public, anon;
grant execute on function public.coe_signature_storage_can_write(text,text) to authenticated;

drop policy if exists coe_signatures_select on storage.objects;
create policy coe_signatures_select
on storage.objects for select
to authenticated
using (bucket_id = 'coe-signatures' and public.coe_signature_storage_can_read(name));

drop policy if exists coe_signatures_insert on storage.objects;
create policy coe_signatures_insert
on storage.objects for insert
to authenticated
with check (bucket_id = 'coe-signatures' and public.coe_signature_storage_can_write(name,'INSERT'));

drop policy if exists coe_signatures_update_profile on storage.objects;
create policy coe_signatures_update_profile
on storage.objects for update
to authenticated
using (bucket_id = 'coe-signatures' and public.coe_signature_storage_can_write(name,'UPDATE'))
with check (bucket_id = 'coe-signatures' and public.coe_signature_storage_can_write(name,'UPDATE'));

drop policy if exists coe_signatures_delete on storage.objects;
create policy coe_signatures_delete
on storage.objects for delete
to authenticated
using (bucket_id = 'coe-signatures' and public.coe_signature_storage_can_write(name,'DELETE'));

commit;
